repos:
-   repo: https://github.com/PyCQA/autoflake
    rev: 'v2.2.0'
    hooks:
      - id: autoflake
        # exclude: ^tests/
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
            "--ignore-init-module-imports",
            "--recursive",
          ]

-   repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        # exclude: ^tests/

-   repo: https://github.com/pre-commit/mirrors-autopep8
    # sha: v1.4.4  # Use the sha / tag you want to point at
    rev: 'v2.0.2'
    hooks:
    -   id: autopep8

-   repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
    -   id: black

-   repo: https://github.com/pre-commit/pre-commit-hooks
    # sha: v1.2.3
    rev: 'v4.4.0'
    hooks:
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: trailing-whitespace

# https://flake8.pycqa.org/en/latest/user/using-hooks.html
-   repo: https://github.com/pycqa/flake8
    rev: '6.0.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        exclude: ^tests/

-   repo: local
    hooks:
    -   id: tests
        name: run tests
        entry: pytest ./tests/
        language: system
        files: '^tests/'
        types: [python]
